source 'https://rubygems.org'

gem 'sinatra'
gem 'activerecord'
gem 'sinatra-activerecord'
gem 'pry-byebug'
gem 'rack'
gem 'rake'
gem 'byebug'
gem 'rack-test'
gem 'pg'
gem 'time_difference'
